version: '3.5'

services:
  db:
    build:
      args:
        DOCKER_DIR: docker/postgres
      context: ..
      dockerfile: docker/postgres/Dockerfile
    environment:
      DB_USER: ws
      DB_USER_PASSWORD: '123456'
      POSTGRES_PASSWORD: '123456'
    hostname: ws_pg
    ports:
      - "5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data


volumes:
  db_vol:




